#!/usr/bin/python

"""General_Vortex2D_PlotModule.py
Danielle McDermott
May 29, 2014

Some general data importing routines... 
need to refer to these rather than earlier copies... 
sigh... Version control
"""

import csv
import numpy as np

'''to do - pass the file pointer after you've opened it, so you are reading from the buffer, rather than reading the same positions over and over.'''

def read_smtest(i,infile='smtest', movie_type="smovie"):
    '''Reads the binary movies generated by Reichhardt MD codes

    optional arguments
    infile='smtest'  default name of almost all movie files

    movie_type="smovie" other options include "cmovie" and "jmovie"
 
    '''

    #better error handling
    with open(infile, 'rb') as fp:
        #fp = file(infile, 'rb')

        fp.seek(0, 2)  # Seek the end
        tot_num_bytes = fp.tell()  # Get the file size
        fp.seek(0, 0)  # Seek the beginning
    
        # open the file, r= for reading, b=binary file

        #get nV
        nV, time = np.fromfile(fp, np.int32, 2)     # read two 32 bit integers
        #print(nV,time)

        interval=1000.0
        #seek the proper position
        num_bytes = int(4*(2 + nV*3) *i/interval)
        print(i,num_bytes,tot_num_bytes)

        if 0: #num_bytes < tot_num_bytes:
            fp.seek(0, 0)  # Seek the beginning    
            print(fp.tell())
            fp.seek(num_bytes,0)    
            print(fp.tell())
        #else:
        #    return
    
        #nV, time = np.fromfile(fp, np.int32, 2)     # read two 32 bit integers
        #print(nV) #,time)
    
        id = np.empty(nV,dtype=np.int32)
        x_array = np.empty(nV,dtype=np.float32)
        y_array = np.empty(nV,dtype=np.float32)
        
        if movie_type == "smovie":
            dtype = np.dtype("i4, (2)f4")
        
        #elif movie_type == "cmovie":
        #    dtype = np.dtype("(2)i4, (2)f4")
        #    type  = np.fromfile(fp, np.int32, 1)[0]
            
        for n in range(nV):        # loop through all particles

            if movie_type == "smovie":
                
                #i,x,y    = np.fromfile(fp, dtype, 1)
                data1 = np.fromfile(fp, dtype, 1) 
                id[n] = data1[0][0]
                x_array[n] = data1[0][1][0]
                y_array[n] = data1[0][1][1]

            #print("line number",fp.tell())

        print(id,x_array,y_array )
        print("final line number",fp.tell())
        
            
    #fp.close()
    return id,x_array, y_array
    
#####################################################
#simple ascii text reader
#####################################################
def import_text(filename, separator):
    '''Simple csv file reader, reads line by line, ignores comments of '#' type

    file_name = absolute name
    separator = ' ', '\t', etc
    '''
    for line in csv.reader(open(filename), delimiter=separator, 
                           skipinitialspace=True):
        if line:
            if line[0].startswith("#"):
                print("")
            elif line:
                #print line
                yield line
    return
#------------------------------------------------------------
#end CSV reader------------------------------------------
#------------------------------------------------------------

def get_data(file_name,columns,sep=' ',path1=''):
    '''Really nice data importer, since it works for any columnar data.

    file_name = "data.txt"
    columns = number of columns in file
    sep = optional, default is space, other could be '\t'
    path1 = path before file name
    '''

    file_name=path1+file_name
    print(path1)
    print(file_name)

    import_data = []

    for i in range(columns):
        import_data.append([])

    for data in import_text(file_name, sep):  
        for i in range(columns):
            import_data[i].append(float(data[i]))
            
    return(np.array(import_data))

###############################################################
def data_read_error(error_code=-1,path=''):
        print("are you in the proper directory?")
        print("please check your data files")

        print("path is:\n", path)
        exit(error_code)
